events {}

http {
    server {
        listen 80;
        server_name airlinev.duckdns.org;

        # Mọi request bắt đầu bằng /.well-known/acme-challenge/ thì nginx sẽ đọc file từ thư mục /var/www/certbot rồi trả về cho thằng request
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;  # thư mục chứa file xác minh của certbot
        }

        location / {
            return 301 https://$host$request_uri; # chuyển hướng tất cả request đến https
        }
    }

    server {
        listen 443 ssl;
        server_name airlinev.duckdns.org; # domain, xử lý request đến từ domain này

        # Trỏ tới cert (nginx đọc từ volume certbot_certs mount tại /etc/letsencrypt)
        ssl_certificate     /etc/letsencrypt/live/airlinev.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/airlinev.duckdns.org/privkey.pem;
        
        # Request có đường dẫn bắt đầu bằng /api/ đến từ domain airlinev.duckdns.org và từ port 80 sẽ được chuyển tiếp đến http://backend:8080, đồng thời cắt bỏ /api
        location /api/ {
            proxy_pass http://backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /admin/auth/ {
            proxy_pass http://backend:8080;          
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://frontend:3000;  
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}