{
 "title": "AirlineV Backend",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate (req/s) theo route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Latency p95 (giay) theo route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Resident memory (RAM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"airline-backend\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "CPU usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"airline-backend\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}